I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 5, in script
    define config.start_label = "start"
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
Exception: config.start_label is not a known configuration variable.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 5, in script
    define config.start_label = "start"
  File "D:\DOWNLOADS\renpy-8.3.6-sdk\renpy\ast.py", line 2248, in execute
    self.set()
  File "D:\DOWNLOADS\renpy-8.3.6-sdk\renpy\ast.py", line 2266, in set
    ns.set(self.varname, value)
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
  File "D:\DOWNLOADS\renpy-8.3.6-sdk\renpy\defaultstore.py", line 101, in __setattr__
    raise Exception('config.%s is not a known configuration variable.' % (name))
Exception: config.start_label is not a known configuration variable.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.6.25022803
SMK Telkom Jakarta 1.0
Tue Mar 11 02:00:46 2025
